export const finnishAuthLocalization = {
  ALREADY_HAVE_AN_ACCOUNT: "Onko sinulla jo tili?",
  DONT_HAVE_AN_ACCOUNT: "Eikö sinulla ole tiliä?",
  CONFIRM_PASSWORD: "Vahvista salasana",
  CONFIRM_PASSWORD_PLACEHOLDER: "Vahvista salasana",
  CONFIRM_PASSWORD_REQUIRED: "Salasanan vahvistus vaaditaan",
  CONTINUE: "Jatka",
  EMAIL: "Sähköposti",
  EMAIL_PLACEHOLDER: "nimi@example.com",
  EMAIL_REQUIRED: "Sähköposti vaaditaan",
  EMAIL_VERIFICATION: "Sähköpostin vahvistus",
  EMAIL_VERIFICATION_DESCRIPTION:
    "Tarkista sähköpostisi ja syötä vahvistuskoodi rekisteröinnin viimeistelemiseksi.",
  EMAIL_VERIFICATION_SUCCESS: "Sähköposti vahvistettu.",
  FORGOT_PASSWORD: "Unohtuiko salasana",
  FORGOT_PASSWORD_ACTION: "Lähetä palautuslinkki",
  FORGOT_PASSWORD_DESCRIPTION: "Syötä sähköpostisi salasanan palauttamiseksi",
  FORGOT_PASSWORD_EMAIL: "Tarkista sähköpostistasi salasanan palautuslinkki.",
  FORGOT_PASSWORD_LINK: "Unohtuiko salasana?",
  GO_BACK: "Takaisin",
  IS_INVALID: "on virheellinen",
  IS_REQUIRED: "vaaditaan",
  NAME: "Nimi",
  NAME_PLACEHOLDER: "Nimi",
  NEW_PASSWORD: "Uusi salasana",
  NEW_PASSWORD_PLACEHOLDER: "Uusi salasana",
  NEW_PASSWORD_REQUIRED: "Uusi salasana vaaditaan",
  OR_CONTINUE_WITH: "Tai jatka palvelulla",
  PASSWORD: "Salasana",
  PASSWORD_PLACEHOLDER: "Salasana",
  PASSWORD_REQUIRED: "Salasana vaaditaan",
  PASSWORDS_DO_NOT_MATCH: "Salasanat eivät täsmää",
  REMEMBER_ME: "Muista minut",
  RESEND_CODE: "Lähetä koodi uudelleen",
  RESEND_VERIFICATION_EMAIL: "Lähetä vahvistusviesti uudelleen",
  RESET_PASSWORD: "Palauta salasana",
  RESET_PASSWORD_ACTION: "Tallenna uusi salasana",
  RESET_PASSWORD_DESCRIPTION: "Syötä uusi salasanasi alle",
  RESET_PASSWORD_SUCCESS: "Salasana palautettu",
  REQUEST_FAILED: "Pyyntö epäonnistui",
  SIGN_IN: "Kirjaudu",
  SIGN_IN_ACTION: "Kirjaudu sisään",
  SIGN_IN_DESCRIPTION: "Syötä sähköpostisi ja salasanasi kirjautuaksesi",
  SIGN_IN_WITH: "Kirjaudu palvelulla",
  SIGN_OUT: "Kirjaudu ulos",
  SIGN_UP: "Rekisteröidy",
  SIGN_UP_ACTION: "Luo tili",
  SIGN_UP_DESCRIPTION: "Syötä tietosi luodaksesi tilin",
  SIGN_UP_EMAIL: "Tarkista sähköpostistasi vahvistuslinkki.",
  VERIFY_YOUR_EMAIL: "Vahvista sähköpostisi",
  VERIFY_YOUR_EMAIL_DESCRIPTION:
    "Vahvista sähköpostiosoitteesi. Tarkista saapuneet viestit. Jos et saanut viestiä, lähetä se uudelleen alla olevasta painikkeesta.",
  USER_ALREADY_EXISTS: "Käyttäjä on jo olemassa",
  INVALID_PASSWORD: "Virheellinen salasana",
  INVALID_EMAIL: "Virheellinen sähköposti",
  INVALID_EMAIL_OR_PASSWORD: "Virheellinen sähköposti tai salasana",
  INVALID_TOKEN: "Virheellinen tunniste",
  EMAIL_NOT_VERIFIED: "Sähköpostia ei ole vahvistettu",
  PASSWORD_TOO_SHORT: "Salasana on liian lyhyt",
  PASSWORD_TOO_LONG: "Salasana on liian pitkä",
  TOO_MANY_ATTEMPTS: "Liian monta yritystä",
  SESSION_EXPIRED: "Istunto vanhentui. Kirjaudu uudelleen.",
  UNAUTHORIZED_SESSION: "Luvaton tai virheellinen istunto",
};
